### ISSUE TITLE
Return informations about the minimisation

### ISSUE THREAD

**Issue by lpatiny** [mljs/fcnnls#12]
```
return {
  result: [],
  info: {
    gradients: [], // array of the gradient at each iteration
    nbIterations: 123, // the number of iterations that was actually done.
  }
}
```

**Comment by santimirandarp** [comment]
Is the `info` field expected to be optional, so that users could still get the same output (plain result, with no object returned), and using `info: true` return the object, or do you want the object by default, as unique output ?
