### ISSUE TITLE
Can not add mljs-bot as owner on npm

### ISSUE THREAD

**Issue by lpatiny** [mljs/fcnnls#8]
I'm not able to add mljs-bot as owner on the npm repository

https://www.npmjs.com/package/ml-fcnnls

And therefore the automatic release using release-please does not work.

@targos could you help me on this ?

```bash
fcnnls [master] % npm owner add mljs-bot
npm ERR! code EOWNERMUTATE
npm ERR! Failed to update package: "403 Forbidden - PUT https://registry.npmjs.org/ml-fcnnls/-rev/11-3cda4140ff295b6347a61a9e5e9c3a59 - Forbidden"
```

Moreover cheminfo-bot is an owner of this package on npm.

**Comment by targos** [comment]
You shouldn't add the bot as owner, but add the package to the mljs npm organization

**Comment by targos** [comment]
I just did it and tried to rerun the workflow but now it says that it was already published...
