### ISSUE TITLE
Examples that do not converge

### ISSUE THREAD

**Issue by dbehringer** [mljs/fcnnls#9]
As discussed recently, here 3 examples that do not converge and raise the exception `Maximum number of iterations exceeded`

Code used:
```
console.log(X);
console.log(Y);
const K = fcnnls(X, Y);
```
X and Y are attached in the zip.

[deconv-examples.zip](https://github.com/mljs/fcnnls/files/11848469/deconv-examples.zip)

**Comment by targos** [comment]
This should be fixed in v1.1.4
